<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <AssemblyName>GreenLuma-Manager</AssemblyName>
        <RootNamespace>GreenLuma_Manager</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>icon.ico</ApplicationIcon>
        <Version>1.0.0-rc2.21</Version>
        <FileVersion>0.0.0.2</FileVersion>
        <AssemblyVersion>0.0.0.2</AssemblyVersion>
        <Copyright>Copyright © 3vil3vo 2026</Copyright>
        <PackageIcon>icon.ico</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/3vil3vo/GreenLuma-Manager</RepositoryUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
        <PlatformTarget>x64</PlatformTarget>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>false</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
        <WebView2NeverCopyLoaderDllToOutputDirectory>true</WebView2NeverCopyLoaderDllToOutputDirectory>
        <TieredPGO>true</TieredPGO>
        <PublishReadyToRun>true</PublishReadyToRun>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" ExcludeAssets="native" GeneratePathProperty="true"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1"/>
        <PackageReference Include="SharpCompress" Version="1.0.0"/>
        <PackageReference Include="SteamKit2" Version="3.4.0"/>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="icon.ico"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Data\steam_applist_legacy.json"/>
        <EmbeddedResource Include="Data\AppList.template.ini"/>
        <EmbeddedResource Include="$(PkgMicrosoft_Web_WebView2)\runtimes\win-x64\native\WebView2Loader.dll">
            <LogicalName>GreenLuma_Manager.Native.WebView2Loader.dll</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <None Update="icon.ico">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Update="LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Update="README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>
